In [ ]:
File Handling in Python
Python too supports file handling and allows users to handle files i.e., 
to read and write files,along with many other file handling options,
to operate on files.
like other concepts of Python, this concept here is also easy and short.

In [ ]:
Working of open() function

Before performing any operation on the file like reading or writing,
first, we have to open that file. For this, 
we should use Python’s inbuilt function open() but at the time of opening, 
we have to specify the mode, which represents the purpose of the opening file.

f = open(filename, mode)

Where the following mode is supported:

r: open an existing file for a read operation.
w: open an existing file for a write operation.
    If the file already contains some data then it will be overridden.
a:  open an existing file for append operation. It won’t override existing data.
r+: To read and write data into the file.
    The previous data in the file will be overridden.
w+: To write and read data. It will override existing data.
a+: To append and read data from the file. It won’t override existing data.



In [1]:
# a file named "sample1.txt", will be opened with the reading mode.
file = open('D:\Deepika M P\PYTHON\Files\sample1.txt', 'r')
# This will print every line one by one in the file
for each in file:
    print(each)

hi hello... first line.



In [2]:
# Python code to illustrate read() function
file = open("D:\Deepika M P\PYTHON\Files\sample1.txt", "r")
print (file.read())

hi hello... first line.



In [3]:
#Another way to read a file is to call a certain number of characters 
# Python code to illustrate read() mode character wise
file = open("D:\Deepika M P\PYTHON\Files\sample1.txt", "r")
print (file.read(5))

hi he


In [ ]:
Creating a file using write() 

In [4]:
# Python code to create a file
file = open('D:\Deepika M P\PYTHON\Files\sample2.txt','w')
file.write("This is the write command.\n")
file.write("It allows us to write in a particular file.\n")
file.close()

#The close() command terminates all the resources in use 
#and frees the system of this particular program. 

In [5]:
# Python code to illustrate append() mode
file = open('D:\Deepika M P\PYTHON\Files\sample2.txt','a')
file.write("This will add this line.")
file.close()

In [6]:
# Python code to illustrate with statement
with open("D:\Deepika M P\PYTHON\Files\sample1.txt") as file: 
    data = file.read()
# do something with data
    print(data)

hi hello... first line.



In [7]:
 #Python code to illustrate with statement alongwith write()
with open("D:\Deepika M P\PYTHON\Files\sample1.txt", "a") as f:
    f.write("Hello World!!!")
with open("D:\Deepika M P\PYTHON\Files\sample1.txt") as file: 
    data = file.read()
# do something with data
    print(data)   

hi hello... first line.
Hello World!!!


In [8]:
# Python code to illustrate split() function
#splits the variable when space is encountered
with open("D:\Deepika M P\PYTHON\Files\sample1.txt", "r") as file:
    data = file.readlines()
    for line in data:
        word = line.split()
        print (word)

['hi', 'hello...', 'first', 'line.']
['Hello', 'World!!!']


In [ ]:
Reading and Writing Array Data on Files
reading of the data contained within a file.
writing of data on file.

In data analysis, the analyst have to deal with large amounts of data collected
within arrays.

NumPy provides in this regard a set of functions that allow 
the data analyst to save the results of his calculations
in a text or binary file. 
Similarly, NumPy allows reading and conversion of written data within
a file into an array.

In [ ]:
Loading and Saving Data in Binary Files

NumPy provides a pair of functions called save() and load().

In [ ]:
save()

simply call the save() function, specifying as arguments the name of the file, 
to which .npy extension will be automatically added, and then the array itself.

In [9]:
import numpy as np
data= np.array([[ 0.86466285, 0.76943895, 0.22678279],
[ 0.12452825, 0.54751384, 0.06499123],
[ 0.06216566, 0.85045125, 0.92093862],
[ 0.58401239, 0.93455057, 0.28972379]])
np.save('saved_data',data)

print(data)

[[0.86466285 0.76943895 0.22678279]
 [0.12452825 0.54751384 0.06499123]
 [0.06216566 0.85045125 0.92093862]
 [0.58401239 0.93455057 0.28972379]]


In [ ]:
load()

To recover the data stored within a .npy file, you can use the load() function by
specifying the file name as argument, this time adding the extension .npy.

In [10]:
loaded_data = np.load('saved_data.npy')
loaded_data

array([[0.86466285, 0.76943895, 0.22678279],
       [0.12452825, 0.54751384, 0.06499123],
       [0.06216566, 0.85045125, 0.92093862],
       [0.58401239, 0.93455057, 0.28972379]])

In [ ]:
SAVE AN ARRAY TO A TEXT FILE

savetxt()

Call open(file, mode) with mode as "w" to open the file named file for writing.
Use a for-loop to iterate through each row of the array.
At each iteration, call numpy.savetxt(fname, X) to write the current row X to the opened file fname.

In [11]:
import numpy as np
an_array = np.array([[ 1,2,3],[4,5,6]])
a_file = open("D:\Deepika M P\PYTHON\Files\sample3.txt", "w")
for i in an_array:
    np.savetxt(a_file, i)
a_file.close()


In [ ]:
READ FROM TEXT FILE TO ARRAY

loadtxt()

The resulting text file can be loaded back into an array. 
Call numpy.loadtxt(fname) to load the file named fname into an array

In [12]:
import numpy as np
original_array = np.loadtxt("D:\Deepika M P\PYTHON\Files\sample3.txt").reshape(2, 3)
original_array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
Reading File with Tabular Data

The data that you want to read or save are in textural format (TXT or CSV, for example).
CSV (Comma-Separated Values) format, in which data are collected in a tabular form
and where all values are separated from each other by commas.

To be able to read your data in a text file and insert them into an array, 
NumPy provides a function called genfromtxt().

The basic syntax of the NumPy genfromtxt function:

numpy.genfromtxt(fname, dtype= ,  comments: , delimiter = , skiprows = , skip_header = , autostrip  =)


numpy.genfromtxt represents the function which reads the input data or file 
which contains various data types into array format.

fname is the filename of the input data or file we are passing through the genfromtxt function. 
It can be given in filename, list or path to read.

dtype is the data type declaration when we want the output array of the genfromtxt function in 
that particular data type. 
If we declare the dtype as ‘None’ it will automatically generate data type depending on
the values of that columns.

comments it is used in indicating the starting characters in a line of the given input data.
We can discard the values or characters that comes after our declared comment.

delimiter its the string value we declared to split the input values.
For csv file we give delimiter as ‘,’ (comma) to separate the values in the file.

skiprows is used to skip a particular rows or a set of rows in the given input file.

skip_header is used when we wanted to skip the starting rows or lines of the given input file.

autostrip it can be declared to automatically remove the white spaces present in between the values
in our data file.

This function performs implicitly two loops:
    the first reads a line at a time, and 
    the second separates and converts the values contained in it,
    inserting the consecutive elements created specifically.
    One positive aspect of this feature is that if within the file there are some missing data,
    the function is able to handle them.

In [15]:
import numpy as np
inp_data = np.genfromtxt("D:\Deepika M P\PYTHON\Files\sample2.txt",dtype=str, delimiter=",")
inp_data

array(['This is the write command.',
       'It allows us to write in a particular file.',
       'This will add this line.'], dtype='<U43')

In [14]:
import numpy as np
inp_data = np.genfromtxt("D:\Deepika M P\PYTHON\Files\sample6.csv",dtype=int, delimiter=",", skip_header=1)
inp_data

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])